"""migrate legacy operations

Revision ID: 4c40da42cc1b
Revises: 54c369544904
Create Date: 2026-08-27 16:48:21.351104

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c40da42cc1b"
down_revision: str | Sequence[str] | None = "54c369544904"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "express_carriers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("identify_column", sa.String(length=80), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "express_charge_prices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("express_type", sa.String(length=20), nullable=False),
        sa.Column("charge_price", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("express_type"),
    )
    op.create_table(
        "query_configs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("group_name", sa.String(length=100), nullable=False),
        sa.Column("query_name", sa.String(length=100), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("sql_content", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_query_configs_group_name"), "query_configs", ["group_name"], unique=False
    )
    op.create_table(
        "salary_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("team", sa.String(length=50), nullable=False),
        sa.Column("year_month", sa.String(length=7), nullable=False),
        sa.Column("base_salary", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("bonus", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("deduction", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_salary_records_year_month"), "salary_records", ["year_month"], unique=False
    )
    op.create_table(
        "stored_files",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("period", sa.String(length=20), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("relative_path", sa.String(length=500), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("file_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("relative_path", name="uq_stored_file_path"),
    )
    op.create_index(op.f("ix_stored_files_category"), "stored_files", ["category"], unique=False)
    op.create_index(op.f("ix_stored_files_period"), "stored_files", ["period"], unique=False)
    op.create_index(op.f("ix_stored_files_sha256"), "stored_files", ["sha256"], unique=False)
    op.create_table(
        "system_settings",
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "team_express_prices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("team_name", sa.String(length=100), nullable=False),
        sa.Column("st_fee", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("st_avg", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("st_extra", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("zt_fee", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("zt_avg", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("zt_extra", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_name"),
    )
    op.create_table(
        "job_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_type", sa.String(length=40), nullable=False),
        sa.Column("period", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("elapsed_seconds", sa.Integer(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_runs_job_type"), "job_runs", ["job_type"], unique=False)
    op.create_index(op.f("ix_job_runs_period"), "job_runs", ["period"], unique=False)
    op.create_index(op.f("ix_job_runs_status"), "job_runs", ["status"], unique=False)
    op.create_table(
        "team_special_rules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("xixi_1kg_unit_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("special_note", sa.String(length=255), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["team_id"], ["team_express_prices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team_special_rules")
    op.drop_index(op.f("ix_job_runs_status"), table_name="job_runs")
    op.drop_index(op.f("ix_job_runs_period"), table_name="job_runs")
    op.drop_index(op.f("ix_job_runs_job_type"), table_name="job_runs")
    op.drop_table("job_runs")
    op.drop_table("team_express_prices")
    op.drop_table("system_settings")
    op.drop_index(op.f("ix_stored_files_sha256"), table_name="stored_files")
    op.drop_index(op.f("ix_stored_files_period"), table_name="stored_files")
    op.drop_index(op.f("ix_stored_files_category"), table_name="stored_files")
    op.drop_table("stored_files")
    op.drop_index(op.f("ix_salary_records_year_month"), table_name="salary_records")
    op.drop_table("salary_records")
    op.drop_index(op.f("ix_query_configs_group_name"), table_name="query_configs")
    op.drop_table("query_configs")
    op.drop_table("express_charge_prices")
    op.drop_table("express_carriers")
    # ### end Alembic commands ###
